version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
    - gabo89
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
